classifier_model_path: "edge_model/classification/models/classifier_int8.onnx"
extractor_model_paths:
  arztbesuchsbestaetigung: "edge_model/extraction/models/arztbesuch/onnx/quantized/model.onnx"
  reisekostenbeleg: "edge_model/extraction/models/reisekosten/onnx/quantized/model.onnx"
  lieferschein: "edge_model/extraction/models/lieferschein/onnx/quantized/model.onnx"
extractor_tokenizer_paths:
  arztbesuchsbestaetigung: "edge_model/extraction/models/arztbesuch/onnx/quantized/"
  reisekostenbeleg: "edge_model/extraction/models/reisekosten/onnx/quantized/"
  lieferschein: "edge_model/extraction/models/lieferschein/onnx/quantized/"
schemas_dir: "data/schemas"
confidence_threshold: 0.7
use_ocr: true
