classifier_model_path: "edge_model/classification/models/classifier_int8.onnx"
extractor_model_paths:
  arztbesuchsbestaetigung: "edge_model/extraction/models/arztbesuch/model.onnx"
  reisekostenbeleg: "edge_model/extraction/models/reisekosten/model.onnx"
  lieferschein: "edge_model/extraction/models/lieferschein/model.onnx"
extractor_tokenizer_paths:
  arztbesuchsbestaetigung: "edge_model/extraction/models/arztbesuch/"
  reisekostenbeleg: "edge_model/extraction/models/reisekosten/"
  lieferschein: "edge_model/extraction/models/lieferschein/"
schemas_dir: "data/schemas"
confidence_threshold: 0.7
use_ocr: true
